FROM python:3.9

RUN apt-get update && apt-get install -y python3-opencv
RUN pip install opencv-python

WORKDIR /usr/src/

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY . .

RUN pip install -r /usr/src/requirements.txt
